# Generated by Django 2.1.8 on 2019-06-03 17:25

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(default='blank/no_img.png', upload_to=gallery.models.album_name),
        ),
    ]
